### PR TITLE
Add random category

### PR DESCRIPTION
**Pull request by Kitefr**
This use the `random.sample` function to get a list of 10 unread random articles.

### CODE REVIEW

**Comment by fniephaus** [comment]
LGTM so far, could you add a test in [test_pocket.py](https://github.com/fniephaus/alfred-pocket/blob/d3fac3795afb6cc577256277ab13ce07fe23c92a/src/test_pocket.py) please?

**Comment by Kitefr** [comment]
I'll try. Never really done unit testing in python. How can i assert randomness in unit testing anyway ?

**Comment by Kitefr** [comment]
I made a unit test for one part of the change but for the other...

**Comment by fniephaus** [comment]
> How can i assert randomness in unit testing anyway ?

Check that all expected items are included without checking the order?

**Comment by Kitefr** [comment]
It seems good now.

**Comment by fniephaus** [comment]
Thanks, I'll take it from here and merge this tomorrow.

**Comment by Kitefr** [comment]
Ok, thank you.

**Pull request merged**
