### PR TITLE
Use url as uid to make alfred sort result automatically.

### PR DESCRIPTION
**Pull request by SFurnace**

### CODE REVIEW

**Comment by fniephaus** [comment]
IIRC, the workflow sorts entries by ID, so links appear as they were saved.
This change will allow Alfred to prioritize links that are more often clicked, right? So it's possible that they don't appear in chronological order anymore?

**Comment by SFurnace** [comment]
Yes, provide uid will let alfred to pick links you use often to the top, and leave other links as usual.

[Link](https://www.alfredapp.com/help/workflows/inputs/script-filter/json/)

**Comment by SFurnace** [comment]
Ah...Sorry, I have made some conflicting changes. I should have done this in other branch. Please close this pull request.

**Comment by fniephaus** [comment]
I've cherry picked https://github.com/fniephaus/alfred-pocket/pull/40/commits/6419df12573d9ad4e3f9b9caa54f935873cba761. It will ship with the next release :)

**Comment by SFurnace** [comment]
👍 :)

**Pull request closed without merging**
